pipeline {
    
    agent any 

    tools { 
        maven 'M2_HOME'
    }

    stages {

        stage('Build') {
            steps {
                sh 'mvn clean'
                sh 'mvn compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
             sh 'mvn package -DskipTests'
            }
        }
    }
}